# Generated by Django 2.2.1 on 2020-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isDelete',
            field=models.IntegerField(choices=[(0, '是'), (1, '否')], default=0, verbose_name='是否删除'),
        ),
    ]
